# Generated by Django 5.2.4 on 2025-07-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('organs', models.CharField(max_length=100)),
                ('date_pledged', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
